name : CD monorepo-v1.1

on : 
  push :
    branches :
      - main
      
jobs :
  cd:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      
      # STEP 1 : BUILD project at github
      - name: BUILD CLIENT FE Project
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build Project
        run: |
            npm install
            npm run build

      # STEP 2 : Copy build file at VPS server
      - name: Deploy Client React App with github action
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          source: "packages/ui-react/build/*"
          target: "/var/www/html/lerna-test.purwadhikabootcamp.com"
      
      # STEP 3 : Copy api project
      - name: Deploy Server API with github action
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          source: "packages/api-express/*"
          target: "/var/www/html/lerna-test-api.purwadhikabootcamp.com"
      
      # STEP 4 : Running API
      - name: Install and Run Server API
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd /var/www/html/lerna-test-api.purwadhikabootcamp.com
            npm install
            pm2 start deploy-staging.config.js