name : CD monorepo-v1.1

on : 
  push :
    branches :
      - main
      
jobs :
  cd:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Check commited before
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd monorepo-lerna
            git add .
            git commit -m "LN-00-server : server commit modified file"
            git pull origin main
            lerna bootstrap --hoist
            echo Comitted Success

      - name: Deploy Lerna-API with github action
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd ./monorepo-lerna/packages/api-express
            pm2 reload lerna-api
            pm2 restart lerna-api
      
      - name: Deploy Lerna-REACT with github action
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd ./monorepo-lerna/packages/ui-react
            npm run build
            rsync -a /root/monorepo-lerna/packages/ui-react/build/ /var/www/html/fp1-test.purwadhikabootcamp.com