name : CD monorepo-v1.1

on : 
  push :
    branches :
      - main
      
jobs :
  cd:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      # STEP 1
      # Mengakses project monorepo yang digunakan
      # Melakukan commit perubahan data project menggunakan git
      # Menjalankan git pull untuk mendapat data project yang terbaru
      # Melakukan instalasi ulang module dengan lerna
      - name: Check commited before
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd monorepo-lerna
            git add .
            git commit -m "LN-00-server : server commit modified file"
            git pull origin main
            lerna bootstrap --hoist
            echo Comitted Success

      # STEP 2
      # Mengakses directory project back-end 
      # Jika pertama kali running action gunakan perintah pm2 start index.js --name project-name
      # Action selanjutnya gunakan pm2 restart project-name 
      - name: Deploy Lerna-API with github action
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd ./monorepo-lerna/packages/api-express
            pm2 restart lerna-api
      
      # STEP 3
      # Membuat directory build FE di NGINX. Gunakan saat pertama kali menggunakan action. 
      # Mengakses project front-end.
      # Menjalankan perintah build react.
      # Menyalin hasil build ke directory NGINX.
      - name: STEP 3 Deploy Lerna-REACT with github action
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          script: |
            # mkdir -p /var/www/html/fp1-test.purwadhikabootcamp.com
            cd ./monorepo-lerna/packages/ui-react
            npm run build
            rsync -a /root/monorepo-lerna/packages/ui-react/build/ /var/www/html/fp1-test.purwadhikabootcamp.com